version: "3.8"

services:
    # PHP service
    php:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
